name: Build firmware
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - moonlander
        keymap:
          - 44key

    steps:
    - name: Checkout QMK Firmware
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Build
      id: build
      run: |
        qmk compile -kb ${{ matrix.keyboard}} -km ${{ matrix.keymap }}
